# OUTPUT
Output demo.gif

# SETTINGS
Set FontSize 18
Set Width 1800
Set Height 1600
Set PlaybackSpeed 0.5
Set TypingSpeed 0.3

# TYPE AND KEYS
Type "go run ."
Sleep 3s
Enter
Sleep 6s

# Send ChatGPT 1 
Enter
Sleep 3s
Type "Describe and compare the different steak cooking methods."
Sleep 3s
Ctrl+S
Sleep 20s
Escape
Sleep 3s

# Send ChatGPT 2
Enter
Sleep 3s
Type "What are coffee varietals? How do their taste differ?"
Sleep 3s
Ctrl+S
Sleep 20s
Escape
Sleep 3s

# View Chat History
Down
Sleep 3s
Enter
Sleep 6s
Enter
Sleep 20s
Escape
Sleep 6s

# END
Ctrl+C






